### PR TITLE
fix current build error>

### PR DESCRIPTION
**Pull request by cru-Luis-Rodriguez**
OK: 8454 distinct packages available
[91mERROR: unsatisfiable constraints:
[0m  python2-2.7.15-r0:
    breaks: world[python=2.7.14-r0]
    satisfies: py-setuptools-33.1.1-r1[python2]
               py2-pip-9.0.1-r1[python2]
               syslog-ng-3.9.1-r1[so:libpython2.7.so.1.0]
The command '/bin/sh -c apk update && apk add -u python=$PYTHON_VERSION py-pip=$PY_PIP_VERSION' returned a non-zero code: 4
Docker image build failed.

### CODE REVIEW

**Comment by cru-Luis-Rodriguez** [comment]
@wrandall22 

could you review? I'm just bumping the Python version from 9.14 to 9.15.  to fix an error on the build.

**Comment by wrandall22** [comment]
How is it that the build started failing without us changing any versions? Is one of the versions of something dynamic in order to require changing the python version for successful build?

**Comment by cru-Luis-Rodriguez** [comment]
Not sure it seems something change in the Jenkins servers :-(

**Comment by mattdrees** [comment]
@SeriousMatt jenkins-prod hasn't been rebuilt recently, has it?

**Comment by mattdrees** [comment]
also, it sounds like that's happening in a docker image build, which doesn't 'see' the jenkins host at all.

**Pull request merged**
